# official tutorial 
# mkdocs-material: https://squidfunk.github.io/mkdocs-material/
# mkdocs: https://www.mkdocs.org/user-guide/configuration/

site_name: Ethereum Study Notes
site_url: https://Yc-Chen.github.io/ethereum-study-notes/
site_author: Yc-Chen
site_description: >-
  Ethereum study notes with code samples.

# Repository
repo_name: Yc-Chen/ethereum-study-notes
repo_url: https://github.com/Yc-Chen/ethereum-study-notes

theme:
  name: material
  language: en
  features:
    - navigation.expand 
    - navigation.sections 
markdown_extensions: 
  - attr_list # https://squidfunk.github.io/mkdocs-material/reference/images/
  - pymdownx.tabbed  # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - nl2br # newline-to-break 
  - toc:
      permalink: '#' # heading anchor 
      slugify: !!python/name:pymdownx.slugs.uslugify # 解决中文标题解析问题
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
plugins:
  - search
  - roamlinks 
  - callouts
  # - privacy:
  #     links_attr_map:
  #       target: _blank
    #- autolinks 
  - exclude:
      glob:
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Yc-Chen/ethereum-study-notes